name: Verify action

on: [push]

env:
  NODE_VERSION: 12.x

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check one, no redirect
      uses: ./
      with:
        url: https://postman-echo.com/status/200
    - name: Check many, no redirect
      uses: ./
      with:
        url: https://postman-echo.com/status/200|https://postman-echo.com/status/304
    - name: Check one, follow redirect
      uses: ./
      with:
        url: https://postman-echo.com/status/200
        follow-redirect: yes
    - name: Check one, with retry
      uses: ./
      with:
        url: https://postman-echo.com/status/200
        max-attempts: 3
        retry-delay: 2s
